### ISSUE TITLE
Please make a script for 65% of the keyboard

### ISSUE THREAD

**Issue by krenXlil** [sukhe/Sukhe-60-percent-keyboard-emulator#1]
Or rather, leave working: arrows, Del, Print Screen. I don't know much about it, but it seems to be easy. If it's not difficult for you to help, I will be very grateful!

**Comment by sukhe** [comment]
I've corrected the syntax to match the 2nd version of AutoHotKey. Now the script is working. At least the part that is responsible for the arrows, del, backspace and printscreen.

I have not had time to completely fix everything, there are several thousand lines of code. So there may be mistakes.
You can turn off extra layers if you don't need them (lines 546-554 of the 'Sukhe_60_percent_keyboard_emulator.ahk')

If the script does not run:
- try adding a directory with *.exe autohotkey files to the antivirus exclusions
- try using AutoHotkey64_UIA.exe instead of AutoHotkey.exe to launch

And further. The latest version of the script is slightly different from the picture on the main page. For example, enter is assigned to 'H', and PageDown is assigned to ';'
There may be other minor differences as well. Too long to redraw the picture.

In any case, you can remap the keys in a way that is more convenient for you.

**Comment by krenXlil** [comment]
Ok, thanks i will try!
